env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: off
  import/extensions: off
  max-len:
    - 1
    - 100
    - ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
